### ISSUE TITLE
An ugly hack for Mobile access. It works! 

### ISSUE THREAD

**Issue by nitinthewiz** [Automattic/liveblog#105]
I've created a menu item to quickly add a liveblog entry. It's good for mobile access but it's an ugly hack, so I'm not asking for a Pull request. I hope the devs can pick it up and clean it... 

The file - 

https://gist.github.com/nitinthewiz/6167179
(Sorry, tried to add code here, but it was looking ugly)
(Save this file as enter-liveblog.php)

Also, the code to add to the liveblog.php file (placed just before the Endif statement)- 

```
add_action( 'admin_menu', 'my_liveblog_page' );

function my_liveblog_page(){
    add_menu_page( 'Add Livepost', 'LivePost', 'edit_posts', 'liveblog', 'add_live_post', '', '4.5' );
}

function add_live_post(){
    //echo "Admin Page Test";   
    include_once( 'enter-liveblog.php'  );
 }
```

Issues - 
1. Hardcoded post ID, didn't know if there is a way to find all posts that are liveblog enabled. Have you made such a function yet?
2. Looks ugly when using with Juiz Smartmobile admin, but is the best way to do it.
3. Opens a tweet intent page, but it's not perfect code. I'd rather have used oAuth but I do not understand that technology.
4. V IMP. I do not fully understand liveblog code, so I have a feeling that the menu item reinitializes every time someone sees my liveblog, which means there's a memory leak in here. I should probably not add the above code to the liveblog.php file but elsewhere. Problem is, where? I do not know. If this is being a mem hog, could the devs help me out in fixing that? 

Thanks for reading.

**Comment by philipjohn** [comment]
Thanks for this! Worth considering as part of #289
