### ISSUE TITLE
Pagination or load more functionality

### ISSUE THREAD

**Issue by henrywright** [Automattic/liveblog#119]
Some of my liveblog posts have 100s of entries. Is there a way to add pagination? Perhaps a load-more button?

**Comment by vincepettit** [comment]
Any news on this feature?

**Comment by philipjohn** [comment]
This isn't a development priority at the moment @vincepettit but we're open to pull requests always

**Comment by danielbachhuber** [comment]
@vincepettit You might want to check out https://github.com/fusioneng/lazyload-liveblog-entries

We didn't get around to releasing to WordPress.org, but we're running the Github version in production.
