### ISSUE TITLE
add_liveblog_to_content filter is inserting duplicate liveblog content in secondary queries

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#140]
The add_liveblog_to_content appends the liveblog content to the end of a post using a filter on the_content. If you have a secondary loop using a custom query that tries to output using the_content(), liveblog content gets duplicated and appears where it shouldn't.

Steps to recreate:
1) Create a secondary query on a liveblog post using "new WP_Query"
2) Output your custom query in a loop using the_content().
3) Notice that the liveblog content is now also appended to your secondary query

I believe that the add_liveblog_to_content function needs to check and make sure that it is only applying itself to the main query on a post.

**Comment by philipjohn** [comment]
Sorry for the late reply - this was fixed in v1.5 by [9f3efc9a2de67089f1d64b901aabd7563d40dee7]
