### ISSUE TITLE
Is the plugin deleting the object cache for each request?

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/liveblog#142]
It seems that on [`liveblog.php L261`](https://github.com/Automattic/liveblog/blob/master/liveblog.php#L261) the object cache for all entries is deleted. This happens at the start of each AJAX request, so _I think_ it means no call to `get_all_entries_asc` will ever be returned from cache (i.e. on [`classes/class-wpcom-liveblog-entry-query.php L101`](https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-entry-query.php#L101)) unless it's within the same request.

Am I reading that correctly?

Is it intentional?

**Comment by philipjohn** [comment]
Unfortunately the code link here is out of date. @simonwheatley Do you happen to recall which code this was referring to?
