### ISSUE TITLE
Custom form fields

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/liveblog#145]
As a publisher who's creating supplemental data to the main liveblog entry, I'd like to have additional text input fields on my liveblog editor.

It _should_ be possible to just wrap the editor in a form, and serialize all of the form fields when the submit button is used.

**Comment by philipjohn** [comment]
I'm taking a look at this, and wondering when this might be useful. Could you provide more context please? That is, of course, if you can still remember 3 years on...

**Comment by GaryJones** [comment]
Closing for lack of feedback.
