### ISSUE TITLE
Templates in theme?

### ISSUE THREAD

**Issue by henrywright** [Automattic/liveblog#150]
I notice Liveblog ships with various templates:
- `/templates/liveblog-form.php`
- `/templates/liveblog-loop.php`
- `/templates/liveblog-single-entry.php`
- `/templates/meta-box.php`
- `/templates/old-wp-notice.php`
- `/templates/restrict-manage-posts.php`

Is it possible to copy these to my theme so that I can modify them? For example:

```
/my-theme/templates/liveblog-form.php
```

**Comment by ahangarha** [comment]
This solution requires make a copy of all templates to the new folder.
How can I just replace one template with my customized one?
