### ISSUE TITLE
1.3.1 release for fixes

### ISSUE THREAD

**Issue by sc0ttkclark** [Automattic/liveblog#172]
Is it possible to push out just fixes for a 1.3.1 release, leaving some of the refactoring for later?

One thing that really bugs (pun intended) me and the error logs are things like this in 1.3 from wordpress.org:

`PHP Strict standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method WPCOM_Liveblog::add_rewrite_rules() should not be called statically in wp-includes/plugin.php on line 470`

I saw the class was fixed just days after the initial 1.3 release from @nb:

https://github.com/Automattic/liveblog/commit/ebff3908807e02dd6fd5d391214c5cd2cfb9330a

Any chances this and maybe a few other fixes can go out while you're working on the next major release? I understand there's lots of things to do and lots of things pulling your time, so I appreciate your consideration in this matter.

**Comment by philipjohn** [comment]
Thanks for the suggestion, and sorry it didn't get a response for so long. This is a good suggestion. I think it's best to avoid minor releases as much as possible unless there is a critical security or serious bug fix. Updates can be a lot of overhead for some users so releasing another version soon after a point release can be a PITA. We'll definitely look a bit more closely at whether we should do a minor release in future, though.
