### ISSUE TITLE
Edited comments appear at end of liveblog after archiving

### ISSUE THREAD

**Issue by adamtow** [Automattic/liveblog#177]
We noticed that if you edit a liveblog comment, it appears twice after the liveblog is archived. The edited comment appears at the bottom of the liveblog (which is now sorted in chrono order). The unedited comment appears in the same place as it originally appeared. According to VIP, 

> This is actually due to how the liveblog plugin "alters" posts and it's by design (oddly enough).
> When a post is edited, the original one is deleted and a new one is added, which has a more
> recent timestamp on it.
> 
> This is done in order to make sure browser caches are updated properly; if you check the GH
> code for Liveblog you'll see it pretty quickly.

One workaround solution is to keep the liveblog active. One would have to add a filter on liveblog_display_archive_query_args that sets the sort order to chrono. To make this elegant for the editors, it would be nice to have the ability to add extra checkboxes and knobs to the liveblog meta box area. I propose adding a do_action to liveblog/templates/meta-box.php wherein plugin developers can add their own metaboxes to control functionality of the liveblog:

do_action( 'liveblog_metabox_display', $state );

where $state is the current state of the liveblog (enabled, archived)

**Comment by ryanmarkel** [comment]
Tested some on ryanmarkel.com (VIP Go site) yesterday and when archiving a liveblog, edits to existing entries show up as their own posts, and they appear chronologically as when they were submitted, which can easily put them out of order.

If you edited an entry more than once before submitting the next one, you get something like this:

https://cloudup.com/iHUQ7O639sD

**Comment by rebeccahum** [comment]
@adamtow @ryanmarkel Are you still experiencing this issue?

**Comment by adamtow** [comment]
The main Recode site is off of WordPress now, so I have not tested if this is still the case. Would be good if it was resolved though.
