### ISSUE TITLE
How to scale liveblog

### ISSUE THREAD

**Issue by gerhardsletten** [Automattic/liveblog#180]
We have a case with a customer that do live coverage of sport-events, and they experience some problems when they have a lot of traffic on post with a live-blog. The rest of the site is cached with Varnish, but the way liveblog query new content, makes it a little hard to do utility varnish since the repeating ajax-queries from the visitors contain a timestamp, so each url will be different. 

Anyone having some suggestion?

**Comment by sboisvert** [comment]
Hi!

Regarding:
>but the way liveblog query new content, makes it a little hard to do utility varnish since the repeating ajax-queries from the visitors contain a timestamp, so each url will be different.

Many of the URLs from the clients should be similar:
https://github.com/Automattic/liveblog/blob/7ad8e9f9bfa0bcd0e45f04531bed422f9fb2c9d2/js/liveblog.js#L201

Are you having too many different urls?

**Comment by nb** [comment]
@gerhardsletten this was [a conscious decision](https://github.com/Automattic/liveblog/blob/master/HACKING.md#major-design-decisions), so that we can cache the queries indefinitely. As @sboisvert mentioned above, a lot of clients will hit the same URL and Varnish’s LRU will take care of the older ones eventually.

**Comment by gerhardsletten** [comment]
@sboisvert and @nb : Thanks will try to add some roles to the varnish-config. Maybe that would be nice to have in some documentation?

But would it be possible to use a socket-request, just pushing updates to users when new updates are added? I NodeJS that seems to be the way of handling real-time data? Or what about long-pulling the request, but that you maybe need some special configuration of the request-timeout in PHP

**Comment by nb** [comment]
@gerhardsletten, unfortunately we use `nginx` cache and not Varnish. But if you contribute a Varnish config we will gladly include it in the docs.

It shouldn't be too hard to make the code work with a websocket or similar method, even if it’s not supported out of the box.

**Comment by gerhardsletten** [comment]
Hi, thanks
They use Nginx, but with Varnish in front, so I think the cache-rule should go into the varnish vlc. There was a rule there not caching 

```
# don't cache ajax requests
if (req.http.X-Requested-With == "XMLHttpRequest") {
	return(pass);
}
```

I updated it like this, and that seem to work:

```
# don't cache ajax requests (except liveblogs)
if (req.http.X-Requested-With == "XMLHttpRequest" && req.url !~ "liveblog") {
	return(pass);
}
```

**Comment by philipjohn** [comment]
@gerhardsletten FYI, we added socket support recently, so feel free to check that out! Thanks for contributing that Varnish config :)
