### ISSUE TITLE
White background colour shouldn't be assumed on highlight fade

### ISSUE THREAD

**Issue by imsimond** [Automattic/liveblog#191]
In `liveblog.js` there are multiple references to `animate({backgroundColor: 'white'}`. This is to gradually remove the yellow highlighting applied to new entries by the `background-color: lightYellow` styling applied to `.liveblog-entry.highlight` in `liveblog.css`.

But this assumes we will always want the background to end up white. We can't make that assumption.
- Not all page backgrounds are white.
- We may want to apply different colourings to different types of `.liveblog-entry`, which this js will override. (We would probably have to start using `!important`, which nobody wants.)

_So what do we do about it?_

We simply shouldn't be hard-coding the white background. I suggest we remove it entirely, but give developers a way to hook an appropriate animated effect in here instead. (To minimise impact on existing users, we could maybe move the effect to a separate file, which developers can easily un/enqueue.)

Whire we're in there, we should probably lose the `.highlight` class once it's served its purpose.

**Comment by philipjohn** [comment]
Fixed in [10453ce]
