### ISSUE TITLE
Mutliple-word hashtags with hyphens aren't picked up properly

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#199]
It looks like the regex at https://github.com/Automattic/liveblog/blob/develop/classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php#L177 is too simplistic, picking up only on the first "word" after "term-" in the comment content.

E.g., https://regex101.com/r/yH0aZ8/1

**Comment by philipjohn** [comment]
@jasonagnew @markgoodyear Any chance you could take a quick look at this regex please?

**Comment by jasonagnew** [comment]
@philipjohn Sorry it took me a bit to pick this up, I'm currently out of the country. I've put a note for someone else to take a look. Either @JonMcPartland or @ConnorVG

**Comment by ConnorVG** [comment]
We could switch the regex to /`(?<!\w)term-[^"\s]+/` instead, this would grab all until the end or whitespace?

**Comment by philipjohn** [comment]
Fixed in #201 - thanks for looking guys!
