### ISSUE TITLE
Key Events

### ISSUE THREAD

**Issue by vincepettit** [Automattic/liveblog#207]
Is it possible to add important milestones to the liveblog as has been done with the Key Events feature on this live blog:

![live-blog](https://cloud.githubusercontent.com/assets/530457/10371012/4b769200-6dd9-11e5-88d8-d6ff2caace75.jpg)

Source: http://www.theguardian.com/business/live/2015/oct/08/head-of-vw-america-testifies-us-congress-emissions-live-updates

Each milestone then links through to the relevant post in the timeline, could be very useful for long live blogs to aid the reader to find the most important parts.

**Comment by philipjohn** [comment]
Hi @vincepettit - we actually have this in development right now. If you'd like to try it out, check out the develop branch in your development environment to try it out. Feedback/improvements welcome!

**Comment by philipjohn** [comment]
Noting this was completed in v1.5
