### ISSUE TITLE
Provide admin UI for editing entries

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#216]
There should be an admin UI, probably in the post edit screen, for managing individual liveblog entries.

**Comment by philipjohn** [comment]
Some good related feedback in #79

**Comment by paulschreiber** [comment]
We'd like to perform creation/editing/deletion _only_ in the admin view, and not in the front-end view.

**Comment by paulschreiber** [comment]
This should be considered a security blocker. The front end is not guaranteed to be HTTPS, but the admin UI is (on wordpress.com and VIP Go).

**Comment by philipjohn** [comment]
Closed in favour of #594 which has more detail
