### ISSUE TITLE
Structured Data support

### ISSUE THREAD

**Issue by mjangda** [Automattic/liveblog#232]
Google is piloting structured data support for liveblogs and it'd be really cool if we integrated it: https://developers.google.com/structured-data/carousels/live-blogs

**Comment by maxhartshorn** [comment]
+1

**Comment by philipjohn** [comment]
Oh, is this the same as [live list](https://github.com/Automattic/liveblog/issues/246)?

**Comment by mjangda** [comment]
Live List is an AMP-specific thing. This is a more generic schema thing that can be used on non-AMP stuff (it's still being piloted by Google though so no guarantees that it'll be useful or continue to be supported down the road).

**Comment by justnorris** [comment]
Looks like the live-blogs structured data at google has been closed in favor of AMP: https://developers.google.com/search/docs/data-types/live-coverage

Ticket for adding Schema LiveBlogPosting: #314 
Ticket for adding Google AMP Support: #246 

I think this can be closed as it's no longer relevant.
