### ISSUE TITLE
Remove Key Event from Key Events Widget does not work after entry update

### ISSUE THREAD

**Issue by budzanowski** [Automattic/liveblog#241]
**Steps to reproduce:**
1. Enable Key Events Widget
2. Create entry with /key
3. Update that entry
4. Click X (delete) on Key Events widget for that entry.

**Effect:**
1. Key Event entry is removed from the Key Events Widget
2. Alert with `Error 500 Key Event Not Deleted` is displayed
3. After refresh Key Events is back in the Key Events Widget

**Analysis:**
After updating Key Event Entry in Liveblog this Key Events entry is replaced with updated version with different ID in blog and in Key Events Widget. Clicking delete tries to remove key event meta from the updated Event. Because of how the updates are processed the updated Entry underling `wp_comment` is missing key event meta. This is the underlying source of Alert because we try to delete non existing meta key.
After refresh it works again because how entries are picked for display. Updates are discarded and the original `wp_comments` are chosen for display. We can discard updates because in process of update original `wp_comment` was also changed. This propably should work differently and the updates should be chosen for display. The original `wp_comment` still has `key event meta` so it is again visible.

**Solution:**
To correct this error we should either rewrite which `wp_comments` are chosen for display. Ensure that Key Event update also has key event meta set and that the delete key event action removes `key event meta` in both update and original post.

**Comment by budzanowski** [comment]
This should be related to #213.

**Comment by maxhartshorn** [comment]
FYI we're still having issues with key event deletion. It seems sometimes when we delete a key event it is not deleted. I've replicated on our live site and on our local. My thought is that it's tied to this issue.

Any update on a fix?

**Comment by philipjohn** [comment]
Fixed by #309
