### ISSUE TITLE
Dangerous combination of [liveblog_key_events] shortcode and /key command.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/liveblog#242]
**To reproduce:**
Use Liveblog with Key Events Widget.
Put the following text into Liveblog entry:
`[liveblog_key_events] /key`

**Outcome**
The blog post dies. It becomes unresponsive and it is not possible to refresh the page.

From the point of usability it does not make sense to make such entry but it is possible to do it.

**Comment by philipjohn** [comment]
Yikes.

Probably need to add something like this into the shortcode handler:

```
if ( WPCOM_Liveblog::is_liveblog_post() ) {
    return;
}
```

**Comment by philipjohn** [comment]
Actually, that's not the right conditional. We need an `is_entry()` helper of some sort

**Comment by philipjohn** [comment]
Fixed by #309
