### ISSUE TITLE
Not possible to update entry twice at the same session.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/liveblog#243]
**Steps to reproduce**
1. Create entry
2. Update that entry(do not refresh page afterwards)
3. Update that entry again.
4. Refresh page

**Outcome**
Second update is lost.

**Analysis**
After first update original entry is replaced with update entry. Second update tries to update update entry. When page is refreshed updates are filtered out, and we only see the original entry with text that was applied to this entry by the first update.

**Solution**
When preparing response to update ajax request prepare the request in such a way that it will have original entry id. This way second update will also target original entry.

**Comment by philipjohn** [comment]
Fixed by #309
