### ISSUE TITLE
Prefetched entries are not updated or deleted.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/liveblog#244]
**Steps to reproduce**
1. Add several entries, as much as needed so on refresh they will not be all immediately visible. To show them you are required to press `LOAD MORE ENTRIES..` button.
2. Open second browser window and load post.
3. In the first window remove first entry that is not displayed in the second window.
4. Click `LOAD MORE ENTRIES..` in the second window

**Outcome**
On the second browser the entry that was just deleted is still visible. After page refresh it is not visible.

**Analysis**
Deleted entry was prefetched. Client gets information that there was delete but it only checks elements that are already displayed. Situation is the same for entry update.

Rather small gap but someone may complain.

**Solution**
Check if target entry is in lazyloader prefetched entries. If it is apply update, delete on it.

**Comment by philipjohn** [comment]
Hi @budzanowski - I'm not seeing this issue, following the reproduction steps. Is this still an issue for you?

**Comment by budzanowski** [comment]
Hey @philipjohn  it was my trial project/finding over a year ago and since then I have not touched this :) So if you think that this is OK than probably it is.

**Comment by philipjohn** [comment]
Oh, so it was! Hi :)

Will close this off...
