### ISSUE TITLE
Add support for AMP Live List

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#246]
[AMP Live List](https://www.ampproject.org/docs/reference/extended/amp-live-list.html) could be an interesting way of supporting Liveblogs via AMP.

<strike>It would probably rely on having [WP-API support](https://github.com/Automattic/liveblog/issues/217) first, to give us the necessary endpoints.</strike>

**Comment by maxhartshorn** [comment]
+1 this would be great

**Comment by mikeselander** [comment]
+1 this would be a fantastic addition to the plugin.

**Comment by mjangda** [comment]
Updated the description as the published version of Live List no longer needs a separate endpoint to work so we don't need WP-API support to be in. It just re-fetches the page to get updates so should be much easier to implement.

**Comment by mjangda** [comment]
There's a challenge with how `amp-live-list` works that doesn't quite mesh with our caching strategy on WordPress.com (and likely other sites).

`amp-live-list` fetches the same page and looks for changes on page as their cue for handling new/edited/removed entries.

We cache pages for 5 minutes, which means that `amp-live-list` may not find updates for up to 5 minutes. (On a regular liveblog page, even if you get a cache-served page, the js kicks in and serves up updates).

One option would be to drop the caching TTL or an alternate caching strategy but with the levels of traffic we see on many liveblogs, that may not be a good idea :)

**Comment by philipjohn** [comment]
Done in #450
