### ISSUE TITLE
Is there a way to tell that a shortcode is rendered within a liveblog?

### ISSUE THREAD

**Issue by maxhartshorn** [Automattic/liveblog#249]
I'm wondering if there is a function or query var I can use to detect whether a given shortcode appears inside a liveblog. It would be great to have the ability to render certain shortcodes differently if they appear inside a liveblog.

**Comment by philipjohn** [comment]
This should be possible by hooking into [`do_shortcode_tag`](https://developer.wordpress.org/reference/hooks/do_shortcode_tag/) and using [`is_liveblog_post()`](https://github.com/Automattic/liveblog/blob/08da6cab97da743c18d054c4081c70cf2198a5e7/liveblog.php#L371-L381) to detect if the output is going onto a Liveblog.
