### ISSUE TITLE
How to check liveblog is Enabled or Archive?

### ISSUE THREAD

**Issue by ashokkumar24** [Automattic/liveblog#251]
Using this function is_plugin_active( 'liveblog/liveblog.php' ) I can check plugin is activated or not. But how can i check Liveblog is enabled or Archive?? Please help on this guys.

**Comment by ashokkumar24** [comment]
Using this function is_plugin_active( 'liveblog/liveblog.php' )  I can check plugin is activated or not. But how can i check Liveblog is enabled or Disabled?? Please help on this guys.

**Comment by david-binda** [comment]
Hello @ashokkumar24 . You should be able to take advantage of the `WPCOM_Liveblog::is_liveblog_post` ( see https://github.com/Automattic/liveblog/blob/master/liveblog.php#L367,L377 ) and/or `WPCOM_Liveblog::get_liveblog_state` (see https://github.com/Automattic/liveblog/blob/master/liveblog.php#L390,L410)

I'll go ahead and will close out this issue, but feel free to reopen it, in case it's not working as expected.
