### ISSUE TITLE
Notification bar 

### ISSUE THREAD

**Issue by ashokkumar24** [Automattic/liveblog#255]
Notification bar is not working. How to enable notification bar? I am just pulled this commit 
( c5c737cca52a7f1edb1bbbc382a2310c92508bc1 ). Please help me on this. Thanks :)

**Comment by philipjohn** [comment]
Hi @ashokkumar24 - could you help me out with a bit more information about this issue please?

1. What are you expecting to happen?
2. What actually happens?
3. What are the steps that we can take to reliably reproduce this issue?

Thanks!

**Comment by rebeccahum** [comment]
@ashokkumar24 Are you still experiencing this issue? Notification bar should be enabled by default.

**Comment by ashokkumar24** [comment]
No longer needed. I am closing this issue.
