### ISSUE TITLE
Using deprecated function `vary_cache_on_function`

### ISSUE THREAD

**Issue by mikeselander** [Automattic/liveblog#264]
Hi guys - I'm getting PHP notices thrown on every page load from liveblog pertaining to a deprecated function from `vip-deprecated.php` on a VIP Go local environment. 

`PHP Notice:  vary_cache_on_function is <strong>deprecated</strong> since version 2.0.0 with no alternative available. in /srv/www/mysite/wp-includes/functions.php on line 3709`

It looks like `classes/class-wpcom-liveblog-lazyloader.php` is attempting to call this function which is filling up our debug log.

Let me know if there's anything else that I can do to help track this bug down.

**Comment by david-binda** [comment]
Hey @mikeselander ! Thanks for opening the issue.

Looks like the whole is_robot() method should be implemented via JS rather than in PHP and relying on cache variations.

I'll work on a patch addressing this issue.

**Comment by paulschreiber** [comment]
Ran in to this with 1.8. @philipjohn can we remove the is_robot() check?
