### ISSUE TITLE
Remote managing/publishing of Liveblogs

### ISSUE THREAD

**Issue by mcarli** [Automattic/liveblog#27]
Hi,
today smartphone and tablet is a very important in live coverage events, so i think is important to implement a way for posting via XMLRPC (for example from a custom application, or maybe from Wordpress app).

Liveblog use "comment" as single post element, so i saw  "wp.newComment" method for create a new post in real-time, but wp.newComment create a comment without any chance for hardwrite "comment_type" and "comment_approved" options.

Is not simple to rewrite wp_newComment() (called by wp.newComment method) for setting comment_type and comment_approved because this one use wp_new_comment() that overwrite "comment_approved".

Any suggestion?

**Comment by philipjohn** [comment]
It'd be great to allow remote access to Liveblogs.

It would be preferable to do have custom [WP-API](https://github.com/WP-API/WP-API) endpoints for this, rather than XML-RPC, but perhaps we should accommodate both?

**Comment by philipjohn** [comment]
I'm going to close this because we're building API support #217
