### ISSUE TITLE
WYSIWYG: Icons cut off in MAC OS

### ISSUE THREAD

**Issue by jahvi** [Automattic/liveblog#275]
Some of the icons in the wysiwyg editor are being cut off in the latest versions of Chrome, Safari and Firefox on Mac OS (Sierra).

<img width="231" alt="screen shot 2016-11-12 at 2 46 52 pm" src="https://cloud.githubusercontent.com/assets/661330/20238612/60d6a49c-a8e7-11e6-820c-66cf0ed7d689.png">

I can submit a PR to address this if no one else is working on it at the moment.

**Comment by philipjohn** [comment]
> I can submit a PR to address this if no one else is working on it at the moment.

That would be great, if you're able to!

**Comment by jahvi** [comment]
PR submitted #279 😀
