### ISSUE TITLE
Use custom post type instead of comments

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#282]
Liveblog currently stores entries using the post comments.This is a bit hacky, really, and it'd make more sense for each entry to be a post of a "liveblog" type.

Considerations for making this change include;

* Liveblog entries will need to be linked to the Liveblog post in a way that can be queried efficiently at scale.
* There would need to a migration routine for Liveblogs using comments.
* Comments-based Liveblogs should still work as expected.

**Comment by mjangda** [comment]
Using comments is a very intentional design decision: https://github.com/Automattic/liveblog/blob/master/HACKING.md

**Comment by paulschreiber** [comment]
Please reconsider this decision. Posts have titles, authors, terms and taxonomies. Lots of filters and actions apply to posts and not comments, creating two classes of posts (live blog posts and non-live blog posts).

LivePress uses child posts for live blog entries. We did not experience any caching problems with it.

**Comment by paulschreiber** [comment]
We hit another limitation of this tonight.

* comments are stored with the MySQL type `text`, max 65535 (edited)
* posts are stored with the MySQL type `longtext`, max 4294967295

We had a post that was 235K, and failed to insert as a liveblog entry.

**Comment by paulschreiber** [comment]
Please reopen this. We should fix it for 2.0 (or 1.10).
