### ISSUE TITLE
The Embed(instagram, twiiter and youtube) Functinality not showing when you click on Preview button

### ISSUE THREAD

**Issue by mrpattnaik** [Automattic/liveblog#286]
Steps to reproduce the Issue.
1: Enter Instagram/twitter URL and Click on Preview. the Instagram is not showing on preview screen.

Please find the attached screen shot.
![screen shot enter instagram](https://cloud.githubusercontent.com/assets/4059927/21686635/1fb90686-d334-11e6-9b75-c2f98f2e4493.jpg)
![screen shot preview](https://cloud.githubusercontent.com/assets/4059927/21686645/23efb754-d334-11e6-9a43-e40beeb160e7.jpg)

**Comment by rebeccahum** [comment]
Hi @mrpattnaik, are you still experiencing this issue? If so, what version of the plugin are you using?
