### ISSUE TITLE
Adding Image-Button for mobile device like iphone

### ISSUE THREAD

**Issue by denisblum** [Automattic/liveblog#300]
Dear developer,
i use liveblog for publishing text and images from several events. It will be perfect, if a future version of liveblog contains a button "Select images" and i can choose a image from my mobile phone, like apple. Currently i have to use a laptop. And this is very cumbersome if you are sitting in a stadion.

Or does it works with the current version?

Thankx,
Denis

**Comment by philipjohn** [comment]
Closing in favour of #289
