### ISSUE TITLE
DB Spikes

### ISSUE THREAD

**Issue by andyphillips82** [Automattic/liveblog#305]
Hi, 

We have New Relic installed on our Wordpress install. When we activate the Live Blog plugin, we get intermittent (every 5-10 minutes or so) DB response time spikes by a flood of wp post select queries.

When we deactivate Live Blog, the spikes go away.  Haven't been able to track down exactly where they're coming from in the code, but was wonder if anyone has seen the same behaviour?

WP 4.7.2
Live Blog: 1.5.2

**Comment by philipjohn** [comment]
What queries are present in those spikes? Are they all/mostly Liveblog queries? If so, what's the nature of the queries?

**Comment by andyphillips82** [comment]
Sorry.  Actually realized the spikes were being caused by the FLUSHALL command being sent to our Redis server.  Those flushalls don't happen when Live blog is deactivated.
