### ISSUE TITLE
How to create hook up for publish update

### ISSUE THREAD

**Issue by sushant4anshu** [Automattic/liveblog#308]
I want to handle data myself after update data is added in comment table of WordPress after publishing update using live blog plugin. How will I handle this where to add hook up filters and which hook up filter?

**Comment by sushant4anshu** [comment]
`function live_blog_comment( $comment_ID, $post_id ) {
        $service_url = "https://example.com/apitest/v3/liveblog/";
        try {
                $data = array('postId' => $comment_ID);

                $ch = curl_init( $service_url );
                $payload = json_encode($data);
                curl_setopt( $ch, CURLOPT_POSTFIELDS, $payload );
                curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
                # Return response instead of printing.
                curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
                # Send request.
                $result = curl_exec($ch);
                curl_close($ch);
                # Print response.
                echo "<script>console.log(".$result.")</script>";
        } catch(Exception $e) {
                echo 'Message: ' .$e->getMessage();
        }
 }
add_action( 'liveblog_insert_entry', 'live_blog_comment' ,10, 2);`

I tried this but this gives me
 
`Error : parseerror`

**Comment by philipjohn** [comment]
"Parse error" indicates that there is an issue with the format of the PHP code. A quick read of the code you pasted above suggests this line:

`echo "<script>console.log(".$result.")</script>";`
