### ISSUE TITLE
Stop polling when tab is no longer visible

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/liveblog#310]
Modern browsers have pretty good APIs for detecting when a given tab is visible. 

If a liveblog is not visible, there is not much point in keeping it up to date. Instead, we should detect when the tab is not visible and pause polling.

Then, when the tab becomes visible again, we run a catchup query then resume polling.

This will help save client and server resources when nobody is actually watching it - perhaps you accidentally left the tab open and have forgotten about it, for example.

**Comment by philipjohn** [comment]
Instead of completely stopping polling we could perhaps lower the update interval instead. Some users may deliberately move the Liveblog out of focus and rely on notifications, so completely suspending polling may "break" their experience.

**Comment by philipjohn** [comment]
Done in #309
