### ISSUE TITLE
Send the poll interval in responses, and use that value for next poll

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/liveblog#311]
Currently we define the poll interval once, and use it everywhere. This works for most cases, but breaks down when it is desirable to change the interval during a liveblog.

Scenario:

10k users have opened your liveblog with a 3s poll interval. Suddenly, your server begins to buckle under the load and you want to dial back the interval to keep it happier. Once the change is made, only new visitors or those that refresh will get the new interval - the vast majority of existing viewers will continue with the old interval.

If the desired interval was returned in each response, it could be changed on the fly and affect every connected viewer, which can be the difference between the server falling over or the liveblog working smoothly.

It would also act as a 'kill switch' if the interval was set very high, or at 0.

**Comment by philipjohn** [comment]
We could set the interval with a filter - that way, changing it is easily tracked with VCS and it can also be done globally or per-liveblog.

**Comment by philipjohn** [comment]
Done in #309
