### ISSUE TITLE
Editor bug inside the theme

### ISSUE THREAD

**Issue by xator91** [Automattic/liveblog#312]
Hi, after install this plugin i have some problem with the editor inside the post, how i could fix this problem?

http://ibb.co/j1QgRv

**Comment by xator91** [comment]
Was an incompatibility with advanced ads, but now there is another visual bug. 

https://ibb.co/gjrcGv

**Comment by xator91** [comment]
And when i try to publish something i have "404 Error"

**Comment by philipjohn** [comment]
Hi! This is likely an issue with styling in your theme. Do you see the same behaviour with the default theme? If not, check which styling within your theme are influencing the Liveblog.

**Comment by philipjohn** [comment]
As we haven't heard back, I'll close this off. If this is still an issue in the default theme, come back and re-open the issue and we can debug together.
