### ISSUE TITLE
Image uploads

### ISSUE THREAD

**Issue by nb** [Automattic/liveblog#32]
Currently if we use the liveblog on a mobile device with support for uploading files we can't upload, because we expect them to be dragged and dropped.

If the device doesn't support drag and drop, but supports native uploads, we should show the standard upload button.

**Comment by philipjohn** [comment]
I've tweaked the issue a bit to exclude the "on mobile".

Whatever solution we come up with here should ideally work for all devices, so that we can drag/drop **or** use some sort of uploader.

**Comment by mjangda** [comment]
FWIW, I think the point of the "on mobile" note was that this issue primarily impacts mobile users since they have no way to upload images.

**Comment by denisblum** [comment]
Hi everybody,
any solutions?

**Comment by philipjohn** [comment]
Closing in favour of #289 which covers more than just images
