### ISSUE TITLE
RestAPI requests failing on multisites

### ISSUE THREAD

**Issue by scottlee** [Automattic/liveblog#320]
I've got a subdirectory multisite that's returning returning `false` when attempting to enable liveblogging for a post. 

I've tracked it down some, but still haven't definitively narrowed it down to why. My theory is this; that the `get_post( $post_id )` call within the `admin_set_liveblog_state_for_post()` method is returning false because `WP_Post::get_instance()` (which uses the global var `$wpdb`) is looking in the wrong posts table. So for some reason the `get_post()` that's run from the API POST request isn't properly accounting for the `blog_id`. Instead it's just assuming `*_posts`. And if no post with the ID exists within the `_posts` table it returns false.

I've been able to semi-prove this theory by placing a `switch_to_blog()` call just above the `get_posts()`. 

So giving the above; I have a couple questions. 

- What am I missing? Is this newest version (1.6) still compatible with multisites as it's been in the past?
- Or what about adding a filter within `use_rest_api()` so that ` $use_rest_api` can be set to false so the JS will use the old ajax (`admin_ajax_set_liveblog_state_for_post`) function?

**Comment by philipjohn** [comment]
> `WP_Post::get_instance()` (which uses the global var `$wpdb`) is looking in the wrong posts table

Can you elaborate on why you think that might be the case? For that to be true, I think Liveblog would have somehow switched to the wrong site.

Also, have you checked the URLs that are being hit for the API requests? Are they hitting the right site in the network?

Do other API requests for sites in the network behave as expected?

Thanks!

**Comment by philipjohn** [comment]
Thanks for the detailed steps, @scottlee ! This is perfect.

Can I ask you to check one more thing please? When you click that Activate button in the metabox there should be a request fired off to WordPress - what's the URL? Does it include the subdirectory?

We shouldn't _need_ to do a `switch_to_blog()` anywhere. Instead, I think that metabox request is going to the main site every time instead of the main site, and we just need to fix the URL.

**Comment by scottlee** [comment]
It does not.

Here's the URL I'm seeing locally: `http://temp-multisite.local/wp-json/liveblog/v1/12/post_state`

**Comment by scottlee** [comment]
Just checking in. Any updates? Have you been able to reproduce this?

**Comment by justnorris** [comment]
Hey @scottlee ,
Thank you for the detailed instructions - reproducing the problem was pretty straight forward. I'm going to dig into this a bit more and see what I can do to fix it.

**Comment by scottlee** [comment]
Awesome. Thank you, @justnorris.
