### ISSUE TITLE
WordPress.org Plugin Directory serves 1.6 but stable version is 1.6.1

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/liveblog#327]
I noticed the stable version in `README.md` is 1.6.1 but WordPress.org serves 1.6 in the plugins directory:

![image](https://user-images.githubusercontent.com/36432/34302831-810fd8f2-e6e7-11e7-8d7c-8a3249e6da99.png)

**Comment by philipjohn** [comment]
Yep, looks like that update never got pushed to WordPress.org for some reason. Process fail.

I'm gonna skip it, because 1.7 is about to break through the door...
