### ISSUE TITLE
Switch to time difference instead of absolute timestamp

### ISSUE THREAD

**Issue by nb** [Automattic/liveblog#33]
Because there are many entries posted users care much more how long ago an entry was posted compared to the exact moment in time.

We should switch (at least by default) to showing a time difference, instead of just the absolute timestamp.

**Comment by maxhartshorn** [comment]
@nb This works for the key events box but not for the liveblog itself. It would be very useful if the liveblog could display a time difference instead of an absolute timestamp

**Comment by maxhartshorn** [comment]
@nb The liveblog is currently displaying the absolute time. It is only the key events box that displays relative time.

**Comment by maxhartshorn** [comment]
@nb Can you please confirm the issue? Is this something Automattic is planning to fix? In the case of a large site like ours, with producers spanning multiple time zones, absolute timestamps can be very misleading

**Comment by philipjohn** [comment]
@maxhartshorn What you're seeing does look like a regression. We'll have a fix for that soon.
