### ISSUE TITLE
"false" string appears when Gravatars are disabled

### ISSUE THREAD

**Issue by justnorris** [Automattic/liveblog#336]
When Gravatars are disabled, instead of not showing anything - the plugin prints out "false" as a string in place of the avatar. 

Was reported as a side issue at #333

**Comment by liam-defty** [comment]
@justnorris Sorry, I hadn't realised you had already taken a look at this. It was also happening in the autocomplete in the editor which I have included a fix for in the pull request.

**Comment by justnorris** [comment]
No problem. 
Can you include this typo fix in your pull request too?
 https://github.com/Automattic/liveblog/pull/339/commits/78959aa0c84ac373e3ffd406275b89662c40ff33
