### ISSUE TITLE
WPCOM_Liveblog_Entry::handle_restricted_shortcodes blanks every shortcode

### ISSUE THREAD

**Issue by hrkhal** [Automattic/liveblog#346]
Due to the use of `get_shortcode_regex()` and not checking what's being replacing, every shortcode in a new liveblog entry is being replaced with an empty string with a default install of liveblog 1.7.

It's blanked due to the default restriction set for `liveblog_key_events`, otherwise all shortcodes would be set to whatever first appears `$restricted_shortcodes`.

Luckily the filter can easily be removed but this should be fixed.

https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-entry.php#L314

**Comment by philipjohn** [comment]
Thanks for the report! The fix will ship in 1.7.1 in a few days.
