### ISSUE TITLE
Broken pagination when multiple entries added

### ISSUE THREAD

**Issue by liam-defty** [Automattic/liveblog#348]
The relative pagination system would sometimes lose track of the last rendered entry and total pages, meaning the pagination didn't always work as expected in certain edge cases.

To re-create one example:

- Open two windows with the same live blog.
- Add more entries than the amount per page before the next polling update.
- Go to the second window and wait for the updates to come in.

The last rendered entry in memory will be incorrect, meaning when you go to page two it won't show the correct entries. Also it will prompt you that you have new updates that you have already seen.

**Comment by philipjohn** [comment]
I wasn't fast enough to reproduce this, so I'll just trust you :smile:

**Comment by philipjohn** [comment]
We'll pop this in 1.7.1 in a few days
