### ISSUE TITLE
Why the Twitter tracking script?

### ISSUE THREAD

**Issue by jeremysarber** [Automattic/liveblog#351]
I'm curious to know why the Liveblog plugin needs to add Twitter tracking script to sites.
![screen shot 2018-02-02 at 11 38 50 pm](https://user-images.githubusercontent.com/36094953/35763098-80caece0-0872-11e8-842d-09fbebd94405.png)

**Comment by philipjohn** [comment]
This will be to enable Twitter embeds within Liveblog entries, much like core does. As these can be added in the Liveblog editor after the page has loaded, the plugin needs to load the script just in case Twitter embeds are used at some point in the liveblog.
