### ISSUE TITLE
Show more than 5 entries in one page

### ISSUE THREAD

**Issue by indreksi** [Automattic/liveblog#355]
How can i show more than 5 entries in one page.

By default it shows only 5 last entries.

**Comment by rebeccahum** [comment]
Hi @indreksi,

This is where it sets the number of entries: https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-lazyloader.php#L103 have you tried adding a filter to `liveblog_number_of_entries`?

**Comment by indreksi** [comment]
Wow, thanks. That worked. And don't understand, how i didn't find that :D

**Comment by rebeccahum** [comment]
No worries.  I'll go ahead and close this.  Thanks!
