### ISSUE TITLE
Filters not firing

### ISSUE THREAD

**Issue by philsbury** [Automattic/liveblog#362]
Hi,

I've tried using two of the filters in the plugin, one to add a custom key event just based on the docs and on to show more in the feed, but neither seem to even fire. I've used my own theme and twentyseventeen, also class and non class based application of the filters and nothing seems to work. Am I missing something? Here's what I've tried:

```php
add_filter('liveblog_number_of_default_entries', 'default_entries', 10);

function default_entries(){
  error_log('updating default entries'); // no output 
  return 10;
}

add_filter( 'liveblog_active_commands', 'add_highlight_command', 10 );

function add_highlight_command( $commands ) {
  error_log('highlight'); // no output
  $commands[] = 'highlight';
  return $commands;
}
```

Thanks

**Comment by philipjohn** [comment]
Fixed by #384 but shout if you're still having issues.
