### ISSUE TITLE
As of v1.7 you can no longer specify a custom key events title

### ISSUE THREAD

**Issue by maxhartshorn** [Automattic/liveblog#372]
The documentation states that you can customize the title of the key events box by adding a title attribute to the shortcode:

[liveblog_key_events title="My New Title"]

This feature is no longer available in v1.7 as the title "Key Events" is hard-coded in the React template.

Is it possible to add this customization back in to the next release? Otherwise I would suggest updating the documentation as it is confusing.

**Comment by lidocaine** [comment]
It appears that somewhere between v1.6.1 and v1.7, the content of the Key Events widget moved to being set by React. In `src/react/containers/EventsContainer.js:18`, the title has been hardcoded as Key Events.

I will see if I can create a workaround to pass the custom title to React.

**Comment by lidocaine** [comment]
I took a look and originally tried to figure out a way to pass the custom title data into React; however, in the end, I ended up removing the `<h2>` from the React template and placing it back into `templates/liveblog-key-events.php`.  I've pushed these changes into PR #381; let me know if this works for you, @maxhartshorn

**Comment by philipjohn** [comment]
Fixed by #381
