### ISSUE TITLE
Using Templete

### ISSUE THREAD

**Issue by ahangarha** [Automattic/liveblog#397]
Hi

I have been using this plugin for a while. after latest update, it seems the plugin doesn't read my template. I have set the custom template  using the method mentioned in this comment: https://github.com/Automattic/liveblog/issues/150#issuecomment-50615548

Has there been any change recently on the plugin?

**Comment by philipjohn** [comment]
Yep, with the move to a React-based frontend we've deprecated the original method of templating and will be working on an alternative, which will have a documented migration path.
