### ISSUE TITLE
Numeric entities are chopped up with hashtags

### ISSUE THREAD

**Issue by combs** [Automattic/liveblog#418]
We are seeing some users pasting in rich text that comes with numeric entities, like `&#x27;`

The liveblog plugin is turning them into hashtags 
https://www.washingtonian.com/2018/04/27/chat-ann-limpert-friday-6/

![image](https://user-images.githubusercontent.com/6174018/39376585-33eddf8c-4a20-11e8-854d-6758fa501577.png)

Can the hashtag parsing be improved to prevent this?

**Comment by cain** [comment]
Currently using https://github.com/Automattic/liveblog/commit/712b2119c76007debd92e8725662880b0ac9eaf7 
for a quick fix. Would love to know when this gets fixed in master! :)

**Comment by philipjohn** [comment]
Fixed by #570
