### ISSUE TITLE
fatal error -  Undefined class constant 'key'

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#431]
Just updated to 1.8.1 and am receiving the following fatal errors:

PHP Fatal error:  Uncaught Error: Undefined class constant 'key' in /wp-content/plugins/liveblog/classes/class-wpcom-liveblog-entry-extend-feature-commands.php:193

**Comment by scottblackburn** [comment]
Hi @kevinlisota,

Thanks for logging this, I'm just attempting to reproduce the issue you're seeing but without success. The key constant was changed from lowercase to uppercase for the 1.8.1 release but it appears that all references were updated correctly. Did you update through the dashboard? could you provide some more information on the steps you took to find this error. Thanks in advance.

**Comment by kevinlisota** [comment]
Now I'm having trouble replicating. I wonder if this was a temporary opcache glitch on our end. Closing for now. Will reopen if it comes back.
