### ISSUE TITLE
Is an author selection required?  Getting Uncaught TypeError: Cannot read property 'id' of undefined without one

### ISSUE THREAD

**Issue by corydavidwilliam** [Automattic/liveblog#437]
Is there a way to disable the new author select feature and return to the old fashioned "post as you are logged in as" way?

I'm currently getting the following console error when I attempt to add an entry without selecting an author.  I'd prefer to remove the feature all together.  Maybe I'm missing a filter for this?

<img width="1270" alt="screen shot 2018-05-08 at 8 03 36 am" src="https://user-images.githubusercontent.com/10226464/39758871-bd36b5b0-5296-11e8-9f9f-de1e1050e5fb.png">

**Comment by cain** [comment]
What version are you running?
I'm using master, and don't get an error posting without an author field.

**Comment by corydavidwilliam** [comment]
Strange, I am using 1.8.1

**Comment by corydavidwilliam** [comment]
Found issue #429 . This fixes my issue.
