### ISSUE TITLE
Flush rewrite rules running on every page load - major database performance issue

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#444]
In the 1.8 release, an incorrect comparison operator was introduced in [this commit.](https://github.com/Automattic/liveblog/commit/5be98e929fb10550f06fc3aa1bd98c3318ddf43b)

Specifically this line: https://github.com/Automattic/liveblog/blob/b06af2d4131d8f1a485b82a291731387c47039c9/liveblog.php#L265

The `REWRITES_VERSION` constant is an integer. The WP option value `liveblog_rewrites_version` is a string. The `!==` comparison checks both value and type, and types don't match. The result is that flush_rewrite_rules runs on every page load.

Totally destroys the database on sites with moderate to high traffic, given how database intensive `flush_rewrite_rules` is.

**Comment by philipjohn** [comment]
Fixed by #439

**Comment by kevinlisota** [comment]
This was closed by https://github.com/Automattic/liveblog/pull/439
