### ISSUE TITLE
Crashed my website

### ISSUE THREAD

**Issue by TwoFlags** [Automattic/liveblog#446]
Just tried to use this feature and it crashed my website with some kind of fatal exception error.

**Comment by karelpetrak** [comment]
Same here. Since 1.8 version, activation or update of the plugin results in some parse error that can crash the whole site (in case of update). WP prevents you from activating a newly installed Liveblog plugin though. This is what I got on a clean WP installation with 1.81 (latest) version. No other plugins installed, no data but the prepopulation "Hello world" stuff.

> Parse error: syntax error, unexpected '[' in /...../wp-content/plugins/liveblog/classes/class-wpcom-liveblog-entry.php on line 488

**Comment by philipjohn** [comment]
Hi folks - can you clarify what PHP version you're using please? I suspect that this error is caused by the newer PHP syntax used by the plugin. We no longer support any PHP versions below 5.6, which are all [end of life](http://php.net/supported-versions.php).

**Comment by philipjohn** [comment]
We hadn't documented the minimum PHP version requirement, so apologies for that. The above mentioned pull request fixes that so that we're properly informing folks.

**Comment by TwoFlags** [comment]
Our server is running PHP 7.0

**Comment by philipjohn** [comment]
@TwoFlags Could you share the exact error please? If you have a full stack trace too that'd helpful too. Also the exact steps you took that led to the error so we can try to reproduce and better find the cause.

**Comment by TwoFlags** [comment]
A "full stack trace" sounds like something I'd order at a diner, so can't help you there. Also, can't share the exact error because I didn't take a screen shot of it and don't want to screw up my website again by replicating it. (I already have a bunch of crud showing below the post where I tried to launch a live blog and then archived it. Tried again and archived it again. It's a mess.)

All I did was launch the live blog and immediately got the ugly screen of death.

Thanks for looking into this. I really love the idea of it and used it once when it was still a little buggy. And hope to use it again if it doesn't shut down my site.

**Comment by karelpetrak** [comment]
Hi @philipjohn it's php 5.3.10 in my case. It's a shared webhosting service. I can try to see if I can have it upgraded. Thanks for your help.

**Comment by justnorris** [comment]
@TwoFlags 
> A "full stack trace" sounds like something I'd order at a diner, so can't help you there.
🤣

What @philipjohn is asking is an error message. Something just like @karelpetrak posted - so that we know what to look for. Maybe you can ask your hosting provider for help tracking down that fatal error?
