### ISSUE TITLE
PHP Fatal error: call to a member function get_timestamp() on string

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#468]
Latest version of liveblog (1.8.2) is filling our debug logs with this error.

[24-May-2018 19:20:24 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_timestamp() on string in /var/www/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-entry-query.php:155
Stack trace:
#0 /var/www/wp-content/plugins/liveblog/liveblog.php(438): WPCOM_Liveblog_Entry_Query->find_between_timestamps('', '0', '1527189627')
#1 /var/www/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-rest-api.php(349): WPCOM_Liveblog::get_entries_by_time('0', '1527189627')
#2 /var/www/wp-includes/rest-api/class-wp-rest-server.php(936): WPCOM_Liveblog_Rest_Api::get_entries(Object(WP_REST_Request))
#3 /var/www/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /var/www/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/liveblog/v1/29...')
#5 /var/www/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#6 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply in /var/www/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-entry-query.php on line 155

**Comment by TheCrowned** [comment]
This seems related to a REST request. Do you have any idea of what the request may be/what it may involve?

**Comment by kevinlisota** [comment]
Unable to replicate. This may have been an opcache issue upon updating. Closing for now. Will reopen if it resurfaces.

**Comment by combs** [comment]
we are getting a ton of these too at the same line (class-wpcom-liveblog-entry-query.php:155) whenever we use liveblog. Here is one example.

```

2018/10/05 15:03:36 [error] 5243#5243: *293821 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_timestamp() on string in /home/USER/WEBROOT/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-entry-query.php:155
Stack trace:
#0 /home/USER/WEBROOT/wp-content/plugins/liveblog/liveblog.php(438): WPCOM_Liveblog_Entry_Query->find_between_timestamps('', '0', '1538751875')
#1 /home/USER/WEBROOT/wp-content/plugins/liveblog/classes/class-wpcom-liveblog-rest-api.php(354): WPCOM_Liveblog::get_entries_by_time('0', '1538751875')
#2 /home/USER/WEBROOT/wp-includes/rest-api/class-wp-rest-server.php(936): WPCOM_Liveblog_Rest_Api::get_entries(Object(WP_REST_Request))
#3 /home/USER/WEBROOT/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /home/USER/WEBROOT/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/liveblog/v1/47...')
#5 /home/USER" while reading response header from upstream, client: 127.0.0.1, server: ourpublic.domain, request: "GET /wp-json/liveblog/v1/478710/entries/0/1538751875/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "internal-server.name"

```

We are using a web server cluster with redis caching and sentry + nginx amplify to report these errors out. They are hitting a cluster of mariadb galera sql machines. 

There are a few thousand of these 500 errors per liveblog. It seems like a given call will toss 500s at first, then begin to deliver at some point and return normal JSON. By watching the live log output I was able to see this behavior in my browser: it was tossing 500s for perhaps 60 seconds.
