### ISSUE TITLE
Liveblog Entries endpoint returning empty array of arrays for authors

### ISSUE THREAD

**Issue by juankk** [Automattic/liveblog#487]
in some cases when there is an error getting the user of the comment the endpoint is displaying an array of empty arrays.

![screen shot 2018-06-08 at 4 43 09 pm](https://user-images.githubusercontent.com/893094/41143018-2d616aee-6b3b-11e8-90df-7e319b88c906.png)

We need to apply a filter to the array so that this empty users are not sent in the api response

**Comment by philipjohn** [comment]
> in some cases

Do you have more details about what situation leads to this happening? I'd like us to be able to reliably reproduce this to see why this is blank and fix that rather than just detect and override.

**Comment by GaryJones** [comment]
Closing for lack of feedback.
