### ISSUE TITLE
App.js needs to be reduced (2.24 MB)

### ISSUE THREAD

**Issue by cain** [Automattic/liveblog#492]
### Problem
App.js needs to be reduced for the functionality it provides.

### Solutions
- Multiple node modules need to be moved to dev dependencies.
- **Code splitting for authoring components, especially the EditorContainer (Big performance hit)**
- The `brace` module is just too big for what we are using it for (editor HTML blocks). Probably best to look for an alternate.
- Moment locale is quite large, and I don't think we are using it. Maybe https://www.npmjs.com/package/dateformat
- Immutable is being introduced in multiple locations.
- ~Extract vendors into a separate build file.~ (no need for this since its a single page)
- rxjs global import? https://github.com/Automattic/liveblog/blob/master/src/react/epics/index.js#L1

webpack bundle analyzer: 
**app.js = 2.19mb**
node_modules = 2.09mb
brace = 1.04mb
moment locale = 0.2mb
immutable.js = 50kb * 3
![untitled](https://user-images.githubusercontent.com/15246256/41699378-f1588394-7566-11e8-99de-1330958fb7fb.jpg)

If anyone else has any suggestions please let me know, ill be working on this 😄

**Comment by philipjohn** [comment]
Fixed by #495
