### ISSUE TITLE
LiveBlogPosting schema not included in non-AMP liveblogs

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#505]
The addition of the LiveBlogPosting schema in [1.9rc](https://github.com/Automattic/liveblog/releases/tag/1.9-rc1) adds the metadata only in the AMP version of liveblogs.

The schema isn't an AMP-specific thing so we should add it to the non-AMP version as well.

**Comment by GaryJones** [comment]
[Add filter](https://github.com/Automattic/liveblog/blob/fd833bb0d5788b13e5fc421641491fb185393024/classes/class-wpcom-liveblog-amp.php#L45), and the [callback](https://github.com/Automattic/liveblog/blob/fd833bb0d5788b13e5fc421641491fb185393024/classes/class-wpcom-liveblog-amp.php#L182-L236).

**Comment by GaryJones** [comment]
Self notes:

- The [`class-wpcom-liveblog-entry.php`](https://github.com/Automattic/liveblog/blob/fd833bb0d5788b13e5fc421641491fb185393024/classes/class-wpcom-liveblog-entry.php) no longer appears to be in use.
- The non-AMP template appears to be [built](https://github.com/Automattic/liveblog/blob/fd833bb0d5788b13e5fc421641491fb185393024/src/react/containers/EntryContainer.js#L70-L116) in React.
- Not sure if there's a way to have the creation of the metadata reusably centralised, and then used via React and AMP outputs.
