### ISSUE TITLE
Add an API endpoint for the Rest API to accept Live Blog entries

### ISSUE THREAD

**Issue by apermo** [Automattic/liveblog#518]
https://core.trac.wordpress.org/ticket/44639

As reported here, the Rest API does not accept live blog entries over the comments endpoint.

----
I want to create an entry/comment for the Liveblogging Plugin

The Liveblog Plugin uses comments with a special comment_type liveblog and a special comment_approved liveblog

The rest API WP_REST_Comments_Controller::create_item() has a hardcoded check for a comment type

// Do not allow comments to be created with a non-default type.
if ( ! empty( $request['type'] ) && 'comment' !== $request['type'] ) {
	return new WP_Error( 'rest_invalid_comment_type', __( 'Cannot create a comment with that type.' ), array( 'status' => 400 ) );
}
Why does the comment endpoint except type if it only accepts a single value?
Can you at least add a filter here, maybe like:
$allowed_comment_types = apply_filter( 'fancy_allowed_comment_types_filter_name', [ 'comment' ] );
// Do not allow comments to be created with a non-default type.
if ( ! empty( $request['type'] ) && ! in_array( $request['type'], allowed_comment_types ) ) {
	return new WP_Error( 'rest_invalid_comment_type', __( 'Cannot create a comment with that type.' ), array( 'status' => 400 ) );
}
Extending the whole class, while copying a single function of nearly 150 lines to change a single if statement seems a bit over the top.

---
The suggestions of @flixos90 and @swissspidy where to create a custom endpoint inside this plugin.

**Comment by paulschreiber** [comment]
Please increase the priority of this task from low to "medium" or "high."

**Comment by philipjohn** [comment]
There is already a [crud endpoint](https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-rest-api.php#L85-L117) that can be used to create entries using the REST API.
