### ISSUE TITLE
Consolidate change log links

### ISSUE THREAD

**Issue by GaryJones** [Automattic/liveblog#546]
Each release has _props_ section, with each user having a link. Someone who contributes to multiple releases will have multiple links

It may be easier to manage, and easier to read in a plain text context, to put all the link references at the bottom. That way, if a link needs updating, it's only in one location.

See https://raw.githubusercontent.com/TGMPA/TGM-Plugin-Activation/develop/CHANGELOG.md as an example.

**Comment by philipjohn** [comment]
Nice idea, thanks. Done in [d68afd5]
