### ISSUE TITLE
style amp-custom validation errors in liveblog 1.9.1

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#559]
Upgraded our site to liveblog 1.9.1, which adds liveblog stylesheet information to each page.

AMP pages in 1.9.1 are not validating, either in Google search console AMP tools or in the AMP validator. 

The error is "CSS syntax error in tag 'style amp-custom' - invalid declaration". 

Here are the spots in amp.css throwing the errors.

liveblog-feed.is-loading:after{content:""
liveblog-event:after{content:""
liveblog-hash:before(content"#"
liveblog-event.only-child:before{content:""

Not entirely sure where the error is here, but these validation errors cause AMP pages not to be displayed by Google.

**Comment by earcos** [comment]
Yeap, I had to comment the lines calling AMP functions in liveblog.php. This is nuts.

**Comment by kevinlisota** [comment]
I think [this error](https://github.com/Automattic/liveblog/issues/581) is reporting the same issue.

**Comment by philipjohn** [comment]
Fixed in #586
