### ISSUE TITLE
Replace `@since Unknown.` with correct values

### ISSUE THREAD

**Issue by GaryJones** [Automattic/liveblog#562]
I'm fixing up the PHPCS violations and adding missing DocBlocks.

For functions and methods, that includes adding `@since` annotations. For the sake of breaking down an already large task, I'm leaving them as `@since Unknown.`, and this Issue is for the separate task of looking up when the functions and methods were actually added and updating the annotation as necessary.

**Comment by philipjohn** [comment]
It might be good to have a checklist here, with links to each so that folks can come along and pick them off one-by-one.
