### ISSUE TITLE
WPCOM_Liveblog::get_all_entry_output() appears to be unused

### ISSUE THREAD

**Issue by GaryJones** [Automattic/liveblog#566]
`WPCOM_Liveblog::get_all_entry_output()` appears to be unused within this plugin. May possibly be expected to be used with a theme. 

Can this method be removed?

**Comment by trepmal** [comment]
Related: `WPCOM_Liveblog::get_all_entry_output()` calls the liveblog-loop.php template, which calls `WPCOM_Liveblog_Entry::render()`, which doesn't exist

**Comment by trepmal** [comment]
relevant commit: 51de8e358b74ce7cb7e5b829c3b8d87e2d702989
