### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by GaryJones** [Automattic/liveblog#567]
The only violation that PHPCompatibilityWP is reporting, is here:

https://github.com/Automattic/liveblog/blob/e5dc95289f7cd98d709e58eed9b75c86c8534305/liveblog.php#L910

Should this be `continue 2`?

**Comment by philipjohn** [comment]
> Should this be continue 2?

Yes, looks like it to me from reading the PHP manual on `continue`.

**Comment by GaryJones** [comment]
Fixed by @rebeccahum in #617, and released in Liveblog 1.9.5.
