### ISSUE TITLE
Templating override is not working

### ISSUE THREAD

**Issue by earcos** [Automattic/liveblog#573]
I copied template files to my active theme inside the /liveblog/ folder. The thing is, just as the translation files, this is not working either. Version 1.9.1.

**Comment by paulschreiber** [comment]
Which file(s) did you copy, and what directory did you put them in?

**Comment by earcos** [comment]
All of them.

/liveblog/ directory inside my active theme as instructed in the readme file.

**Comment by earcos** [comment]
sure, 

`domain.com/wp-content/themes/theme-name/liveblog/liveblog-single-entry.php`

**Comment by jonathanstegall** [comment]
I'm having this issue as well, with the same path. I have been unable to see any modifications from editing files in the /theme-name/liveblog folder.

**Comment by tinterweb** [comment]
Same for me. It looks like (I am investigating) the markup in the template is now being bundled up. Is anyone looking into this issue?

**Comment by philipjohn** [comment]
Now that we're using the React-based frontend the PHP templating has been deprecated. We're looking into templating options for an future release.

**Comment by earcos** [comment]
Take 3 minutes into updating the plugin's documentation. It is clearly is confusing a lot of people.
