### ISSUE TITLE
liveblog 1.9 removes wpautop on articles

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#574]
AMP pages are normally rendered with wpautop, changing carriage returns into paragraph tags. (same functionality as non-AMP pages in WP).

Upgrading from 1.8.2 to 1.9 disables wpautop, removing all paragraph breaks and ruining article formatting.

We rolled back from 1.9.1 because of [this error](https://github.com/Automattic/liveblog/issues/559). Now rolling back to 1.8.2 until this AMP functionality is better tested.

**Comment by paulschreiber** [comment]
We just noticed this. `WPCOM_Liveblog_AMP::setup()` should ensure the current post is a liveblog post before running any code.
