### ISSUE TITLE
esc_html() in print_styles() produces invalid CSS

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/liveblog#581]
The change made in b905b57de52e1eae1b305e0ef2c7f5da11966811 results in invalid CSS.

Specifically, in `_feed.scss`, the `.liveblog-feed:before` selector has:
```
content: '';
```

which becomes:
```
content: &quot;&quot;;
```

which is invalid CSS, and fails the AMP validator.

**Comment by philipjohn** [comment]
Fixed in #586
