### ISSUE TITLE
Introduce a "Classic" backend editor

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#595]
## What's the problem?

1. Liveblog currently maintains it's own React-based editor for the frontend. With the introduction of Gutenberg on the horizon, maintaining a separate editor is inefficient.
1. Adding AMP support to Liveblog was a great addition. Any sites that choose to use an AMP Native theme however don't have a frontend editor, because the AMP format doesn't support that.
1. There have been a number of user requests for years for a backend editor.
1. Users who are not yet ready to make the switch to Gutenberg won't benefit from #594

## How do we know this is a problem?

Through it's experience with clients, WordPress.com VIP has taken lots of feedback about the desire for a backend editor. Some Liveblog users have developed their own solutions, sometimes forking Liveblog in the process which adds an extra maintenance burden for them for features that more users would benefit from.

We've spent a lot of time building a React-based editor in order to make the Liveblog editing experience great across mobile as well as desktop. This has added an extra maintenance burden and introduced plenty of bugs.

## What are we doing to solve this problem?

Building a classic-based editor to be used on the backend in the WordPress post editor.

## The bet

We bet that adding a classic-based editor will:

1. Improve maintainability by re-using the WordPress classic editor.
1. Reduce the burden on users of Liveblog who have decoupled setups or prefer (e.g. for security reasons) to edit on the backend.
1. Provide backwards-compatibility for those users who have not yet switched to Gutenberg.

## What’s the vision?

Liveblog users and site owners will be excited to create liveblogs because it's so easy and so familiar.

## Timeline

This will be introduced in [v2.0](https://github.com/Automattic/liveblog/projects/3), scheduled for release at the end of January 2019.

## Acceptance Criteria

- [ ] Users can edit a liveblog from within the post edit screen of the WordPress admin
- [ ] The "Key Events" shortcode can be added to the post
- [ ] Oembeds (such as Twitter, Facebook etc) should all embed as expected
- [ ] Users can mark an entry as a "key event"
- [ ] Users can apply a "slash command" to an event
- [ ] Each entry can have one or more authors
- [ ] The underlying data model remains the same

**Comment by GaryJones** [comment]
Possibly solved with https://github.com/Automattic/liveblog/pull/469

**Comment by GaryJones** [comment]
I'm going to close this out, as this far in, there's a lot less support wanted for a classic editor vs not being able to take advantage of the benefits of the block editor, front or back.
