### ISSUE TITLE
Liveblog not showing on AMP 

### ISSUE THREAD

**Issue by opeedo** [Automattic/liveblog#605]
I just implemented liveblog on my website Naijanews.com however the amp version of my website does not load liveblog. it only displays normal post update.
**Please see example of non-amp page and its amp page below**
**Non AMP  Page**
https://www.naijanews.com/2018/11/17/live-update-kwara-state-bye-election-results/ - Non AMP Page

![screencapture-naijanews-2018-11-17-live-update-kwara-state-bye-election-results-2018-11-19-10_23_54](https://user-images.githubusercontent.com/4742342/48701103-fc736e80-ebed-11e8-8eae-c0dc2a2a972c.png)

AMP enabled page
https://www.naijanews.com/2018/11/17/live-update-kwara-state-bye-election-results/amp - AMP Page

![screencapture-naijanews-2018-11-17-live-update-kwara-state-bye-election-results-amp-2018-11-19-10_24_27](https://user-images.githubusercontent.com/4742342/48703514-3b0c2780-ebf4-11e8-976f-a502ed8f6f3e.png)

**Comment by paulschreiber** [comment]
What troubleshooting steps have you tried?
Are you using custom post types?

**Comment by philipjohn** [comment]
Closing given we haven't heard back in a month. If you're still seeing this issue - please let us know the answers to Paul's questions. Thanks!

**Comment by deepakrohillas** [comment]
As i did check  liveblog not working with  plugin AMP for WP – Accelerated Mobile Pages
By Ahmed Kaludi, Mohammed Kaludi

plugin url  :  https://wordpress.org/plugins/accelerated-mobile-pages/

**Comment by paulschreiber** [comment]
@deepakrohillas Use the official AMP plugin: https://wordpress.org/plugins/amp/
