### ISSUE TITLE
We shouldn't copy/paste wp_max_upload_size()

### ISSUE THREAD

**Issue by nb** [Automattic/liveblog#61]
Currently a `wp_max_upload_size()`, `convert_bytes_to_hr()`, and `convert_hr_to_bytes()` are copied from core, verbatim.

The reason is that before 3.5 they were in `wp-admin/`, but we needed them on the frontend.

Copy-pasting is never the best long-term strategy. Instead, if the functions are missing, we should include the relevant admin file (`wp-admin/includes/template.php`).

**Comment by philipjohn** [comment]
Fixed by #295, due to be released in 1.6
