### ISSUE TITLE
Minified React error #109;

### ISSUE THREAD

**Issue by fuohua** [Automattic/liveblog#611]
Uncaught Error: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=OneCateList for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by paulschreiber** [comment]
This is just an error message. If you want to file an issue about this message, please provide configuration details and reproduction steps.

**Comment by GaryJones** [comment]
Closing for lack of feedback.
