### ISSUE TITLE
it is not issue ,how can we hide author name and image

### ISSUE THREAD

**Issue by deepakrohillas** [Automattic/liveblog#615]
it's not issue , is there any filter to hide author name and image from live blog entry from frontend  for non logged in user.because generally we don't need's to show author name and image in live blog every entry.

**Comment by philipjohn** [comment]
You should be able to simply remove the authors from the entry JSON to exclude from the output.

The `liveblog_entry_for_json` filter will allow you to https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-entry.php#L133-L144, including the authors element before the JSON is sent back to the liveblog.
