### ISSUE TITLE
PHP 7.3 Compat: Continue Targeting Switch issues Warning

### ISSUE THREAD

**Issue by trepmal** [Automattic/liveblog#616]
>  _continue_ statements targeting _switch_ control flow structures will now generate a warning. In PHP such _continue_ statements are equivalent to _break_, while they behave as _continue 2_ in other languages. 

http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

https://github.com/Automattic/liveblog/blob/e049820b1664d4e337858a3490a6e272a010f850/liveblog.php#L914

**Comment by paulschreiber** [comment]
Should this be changed to `break`?

**Comment by trepmal** [comment]
I believe so
