### ISSUE TITLE
Is there any way to support SSR?

### ISSUE THREAD

**Issue by vishaldodiya** [Automattic/liveblog#625]
The entries get added after page loads and for SEO purpose we need the Data to be in the content. Is there any way to resolve this problem.

**Comment by paulschreiber** [comment]
What is SSR?

This ain’t a support forum. If you are making a feature request, please provide more detailed requirements.

**Comment by vishaldodiya** [comment]
Hi @paulschreiber,

I have some questions in general about the SEO of the live blog entries. SSR is Server Side Rendering.

What I am trying to do is, get the live blog comments/entries in the document/markup itself, currently since live blog plugin is using React its not outputting the live blog entries in the markup which is correct. In short, it's not rendered server side but on a news site, we might need these live blog entries in the markup also for SEO purposes. 

So I have a few questions:
1. Does this live blog entries get crawled by Google already given that its rendered using React JS?
2. If not, can we output live blog entries in content ( Hidden ) and then google will get the live blog content?

Thanks in advance.

**Comment by paulschreiber** [comment]
> Does this live blog entries get crawled by Google already given that its rendered using React JS?

Yes.

Example: https://www.google.com/search?ei=5FB4XISnOpKf_QbN54voCg&q=site%3Afivethirtyeight.com+%22Congrats+to+the+Patriots%22&oq=site%3Afivethirtyeight.com+%22Congrats+to+the+Patriots%22&gs_l=psy-ab.3...11033.13623..13892...0.0..0.97.334.4......0....1j2..gws-wiz.......0i71.mz3YfHbuEVY

**Comment by vishaldodiya** [comment]
@paulschreiber 

That's really helpful.
Thanks.
