### ISSUE TITLE
Should release 1.9.5 be deployed to wp.org?

### ISSUE THREAD

**Issue by benlk** [Automattic/liveblog#632]
https://wordpress.org/plugins/liveblog/ shows the most-recent update is 1.9.4, with a "Tested up to" of WP 4.9.10.

This might be a duplicate of https://github.com/Automattic/liveblog/issues/618.

**Comment by GaryJones** [comment]
As 1.9.6 is available on WP.org at the moment (and hopefully soon the tagged 1.9.7), I'll close this out.
