### ISSUE TITLE
Liveblog 

### ISSUE THREAD

**Issue by okupdatenumber** [Automattic/liveblog#656]

**Comment by GaryJones** [comment]
On a minimal site, this activates fine:

<img width="1028" alt="Screenshot 2020-03-30 at 09 47 25" src="https://user-images.githubusercontent.com/88371/77893179-806e4980-726b-11ea-8946-0bff766e1adb.png">


- Using the latest version of WP.
- Using the latest version (`master` branch) of Liveblog.
- Built from source (`npm install, npm run-script build`) to ensure all of the JS files are correctly in place.

I can see from your video that you have other plugins activated, if not a non-default theme active as well, and so you therefore have other custom code that may be affecting. Until you can demonstrate the issue using either the latest tagged release, or the `master` branch, and with all other plugins disabled, then we're not going to be able to reproduce the issue.

Are there any console errors when you try activating liveblog on a post?
