### ISSUE TITLE
Clean comment cache after direct SQL queries

### ISSUE THREAD

**Issue by david-binda** [Automattic/liveblog#657]
Since WordPress 4.6, the `comment` cache group is persistent, thus after any `INSERT`, `UPDATE`, or `DELETE` direct SQL query touching the comments table, the `clean_comment_cache` function should be called.

Looks like it's not the case in Liveblog's WP CLI commands: https://github.com/Automattic/liveblog/blob/master/classes/class-wpcom-liveblog-wp-cli.php#L160

See https://make.wordpress.org/core/2016/07/18/comments-in-4-6-can-now-be-cached-by-a-persistent-object-cache/

**Comment by paulschreiber** [comment]
The updated version of liveblog uses posts instead of comments: https://github.com/paulschreiber/liveblog
which avoids this problem
