### ISSUE TITLE
PHP Warning From dotorg Plugin Version

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/liveblog#665]
There's a discrepancy between the codebase in this repo and the version of the plugin currently available on WP.org, and the version on .org has a single line that throws PHP warnings. 

The warning:
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/htdocs/wp-content/plugins/liveblog/liveblog.php on line 914
```

The offending line:
https://plugins.trac.wordpress.org/browser/liveblog/trunk/liveblog.php#L914

The relevant code in this repo, which doesn't contain the problematic line:
https://github.com/Automattic/liveblog/blob/master/liveblog.php#L903-L913

**Comment by GaryJones** [comment]
Seems to have been addressed.
