### ISSUE TITLE
请问在页面中如何使用liveblog，谢谢！

### ISSUE THREAD

**Issue by jerfo0** [Automattic/liveblog#667]
挺想在页面中使用这个的！

**Comment by BrookeDot** [comment]
Hi there, 

I used Google Translate to translate your question. Currently, we only are able to provide responses in English but I'll do my best to answer you here. Please do reply in English though. 

Once the plugin is installed, you can enable a live blog from the post's edit's page. The documentation also provides a bunch of other filters and options:
https://github.com/Automattic/liveblog

I'll go ahead and close out this issue for now.
