### ISSUE TITLE
Switch front-end code to React

### ISSUE THREAD

**Issue by nb** [Automattic/liveblog#70]
Currently the front-end code is a typical callback jQuery mess. We should switch to ~Backbone~ React to get everything in order.

**Comment by mzahir** [comment]
We would be better positioned to use React instead of Backbone or an older framework

**Comment by philipjohn** [comment]
This is going ahead in 1.7, so these are the features the new UI should carry over from the existing UI:

o Lazy loading entries
o Key events (Q: do we use the shortcode still? What about legacy usage?)
o Slash commands
o Hashtags
o Key event formats
o Entry preview

Other requirements;

o Socket support needs to work with the new UI
o Works well in mobile (#289)

Desirables:

o Formatting toolbar
o Support for inserting images, other than drag-n-drop
o Mobile camera support

**Comment by philipjohn** [comment]
Done in #322
